### ISSUE TITLE
Unable to get the backend running 

### ISSUE THREAD

**Issue by AngularTx** [fluentpos/fluentpos#211]
E:\fluentpos\fluentpos\src\server\API>dotnet watch run
watch : Started
Building...
Unhandled exception. Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
........

Can some one help me here , how this issue could be resolved ?

**Comment by AngularTx** [comment]
closed
